Repository hvac/hvac, pull requests merged in 2018-06, with the labels that each got.

#137 Add Additional Testing for Mount Tuning
  hvac/tests/test_integration.py
  hvac/v1/__init__.py
  test/vault-tls.hcl
Labels: enhancement

#157 Fixed json() from dict bug and added additional arguments on auth_ec2() method
  hvac/tests/test_integration.py
  hvac/v1/__init__.py
Labels: aws, waiting-reply

#174 add transit signature_algorithm parameter
  hvac/v1/__init__.py
Labels: waiting-reply

#170 Add auth_iam_aws() method
  README.md
  hvac/aws_utils.py
  hvac/tests/test_unit.py
  hvac/v1/__init__.py
  requirements-dev.txt
Labels: aws

#197 Always Specify auth_type In create_ec2_role
  hvac/v1/__init__.py
Labels: aws

#140 Support specifying period when creating EC2 roles
  hvac/tests/test_integration.py
  hvac/v1/__init__.py
Labels: aws

#112 Add delete_role method
  hvac/tests/test_integration.py
  hvac/v1/__init__.py
Labels: enhancement, waiting-reply
