Repository hvac/hvac, pull requests merged in 2018-12, with the labels that each got.

#352 fix identity engine double slash
  hvac/api/secrets_engines/identity.py
Labels: bug, identity

#346 Fix identity group conditionals
  hvac/api/secrets_engines/identity.py
  tests/integration_tests/api/secrets_engines/test_identity.py
Labels: bug, identity

#347 Fix For read_health_status() Exception Handling
  .travis.yml
  hvac/adapters.py
  hvac/api/system_backend/health.py
  requirements-dev.txt
  tests/config_files/vault-ha-node1.hcl
  tests/config_files/vault-ha-node2.hcl
  tests/integration_tests/api/system_backend/test_health.py
  tests/scripts/install-consul.sh
  tests/utils/__init__.py
  tests/utils/hvac_integration_test_case.py
  tests/utils/server_manager.py
Labels: bug, system backend

#354 Fix seal_status Call
  hvac/v1/__init__.py
  tests/integration_tests/v1/test_integration.py
Labels: bug, system backend

#348 Fix Request Redirection Handling
  hvac/adapters.py
  tests/unit_tests/test_adapters.py
Labels: bug

#355 Clarify lease docs
  docs/usage/system_backend/lease.rst
Labels: documentation, system backend

#360 Tweak Travis CI Configuration
  .travis.yml
  tox.ini
Labels: CI/CD

#361 Wait for test kvv2 secrets engine to show up in list
  tests/integration_tests/api/secrets_engines/test_kv_v2.py
Labels: CI/CD

#363 Set "skip_missing_interpreters" to true in global tox config
  tox.ini
Labels: CI/CD

#364 Fix For Intermittent Health Test Case Failure
  tests/integration_tests/api/system_backend/test_health.py
  tests/utils/hvac_integration_test_case.py
Labels: CI/CD

#365 Simplify flake8 env for travis-ci + tox
  .travis.yml
  tox.ini
Labels: CI/CD

#370 Add AWS Secrets Engine Class
  docs/usage/secrets_engines/aws.rst
  docs/usage/secrets_engines/index.rst
  hvac/api/secrets_engines/__init__.py
  hvac/api/secrets_engines/aws.py
  hvac/api/secrets_engines/identity.py
  hvac/constants/aws.py
  tests/integration_tests/api/secrets_engines/test_aws.py
  tests/unit_tests/api/secrets_engines/test_aws.py
  tests/utils/hvac_integration_test_case.py
Labels: aws, secrets engines
