Repository hvac/hvac, pull requests merged in 2019-03, with the labels that each got.

#403 AWS: ensure request parameters are sent with generate_credentials
  hvac/api/secrets_engines/aws.py
  tests/integration_tests/api/secrets_engines/test_aws.py
Labels: aws

#375 Fix delete_role_secret_id_accessor method
  hvac/v1/__init__.py
  tests/unit_tests/v1/test_approle_routes.py
Labels: auth methods

#377 #376 : fix length in transit.generate_random_bytes()
  hvac/api/secrets_engines/transit.py
Labels: transit

#393 Add possibility to specify type in create_token
  hvac/v1/__init__.py
Labels: token

#413 Update Readme + Add Doctests
  README.md
  docs/conf.py
  docs/index.rst
  docs/overview.rst
  docs/readme.rst
  hvac/api/secrets_engines/kv.py
  hvac/api/system_backend/init.py
  hvac/api/system_backend/mount.py
  hvac/api/system_backend/seal.py
  hvac/utils.py
  tests/config_files/vault-doctest.hcl
  tests/doctest/__init__.py
  tests/integration_tests/api/auth_methods/test_ldap.py
  tests/utils/mock_ldap_server.py
  tests/utils/server_manager.py
  tox.ini
Labels: documentation

#417 Revert "Fix recovery_threshold / recovery_shares conditional"
  hvac/api/system_backend/init.py
Labels: bug
