Repository hvac/hvac, pull requests merged in 2019-07, with the labels that each got.

#485 Set up release-drafter / _mostly_ automated releases
  .github/release-drafter.yml
  .travis.yml
  CONTRIBUTING.md
Labels: enhancement

#482 Expanded Support for AWS Auth Method
  hvac/api/auth_methods/__init__.py
  hvac/api/auth_methods/aws.py
  hvac/constants/aws.py
  hvac/v1/__init__.py
Labels: auth methods, aws, enhancement

#487 GCP Auth Test Case Updates For Changes in Vault v1.1.1+
  tests/integration_tests/api/auth_methods/test_gcp.py
Labels: CI/CD, bug

#488 Update Travis CI Test Matrix With Latest Vault Version & Drop Python 3.6
  .travis.yml
  tests/scripts/install-vault.sh
  tests/utils/__init__.py
Labels: CI/CD, misc

#486 Numerous Fixes and Doctest Support for Transit Secrets Engine
  docs/usage/secrets_engines/transit.rst
Labels: documentation, transit

#478 Start Using Enterprise (Trial) Version of Vault For Travis CI Builds
  .travis.yml
  CONTRIBUTING.md
  tests/scripts/install-vault.sh
  tests/utils/__init__.py
  tests/utils/hvac_integration_test_case.py
Labels: CI/CD, enterprise, misc

#489 Add Create and List Namespace System Backend Methods
  hvac/api/system_backend/__init__.py
  hvac/api/system_backend/namespace.py
  tests/integration_tests/api/system_backend/test_namespace.py
Labels: enhancement, namespace, system backend

#490 Additional Travis CI Deployment Bits
  .travis.yml
  CONTRIBUTING.md
Labels: CI/CD, misc, skip-changelog

#492 Fix overlapping job includes
  .travis.yml
Labels: CI/CD, misc, skip-changelog

#491 Release v0.9.3
  .bumpversion.cfg
  .github/release-drafter.yml
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  docs/conf.py
  docs/usage/secrets_engines/transit.rst
  hvac/api/auth_methods/__init__.py
  hvac/api/auth_methods/aws.py
  hvac/api/secrets_engines/aws.py
  hvac/api/system_backend/__init__.py
  hvac/api/system_backend/capabilities.py
  hvac/api/system_backend/namespace.py
  hvac/constants/aws.py
  hvac/v1/__init__.py
  setup.py
  tests/integration_tests/api/auth_methods/test_gcp.py
  tests/integration_tests/api/system_backend/test_namespace.py
  tests/scripts/install-vault.sh
  tests/unit_tests/api/secrets_engines/test_aws.py
  tests/utils/__init__.py
  tests/utils/hvac_integration_test_case.py
Labels: release, skip-changelog

#494 Add a Codeowners file for automatic reviewer assignments
  .github/CODEOWNERS
Labels: meta, misc

#495 Add config for updatedocs app
  .github/config.yml
Labels: meta, misc

#502 Fix consul secret engine return values
  hvac/api/secrets_engines/consul.py
Labels: bug

#500 Add delete_namespace Method and Establish Namespace Documentation
  CONTRIBUTING.md
  docs/usage/system_backend/namespace.rst
  hvac/api/system_backend/namespace.py
Labels: enhancement, namespace

#504 Release v0.9.4
  .bumpversion.cfg
  .github/CODEOWNERS
  .github/config.yml
  CHANGELOG.md
  CONTRIBUTING.md
  docs/conf.py
  docs/usage/system_backend/namespace.rst
  hvac/api/secrets_engines/consul.py
  hvac/api/secrets_engines/database.py
  hvac/api/system_backend/namespace.py
  setup.py
Labels: release, skip-changelog

#508 Add Active Directory Secrets Engine Support
  hvac/api/secrets_engines/__init__.py
  hvac/api/secrets_engines/active_directory.py
Labels: enhancement, secrets engines

#509 Include Recently Added Namespace Documentation In Toctree
  CONTRIBUTING.md
  docs/usage/system_backend/index.rst
  docs/usage/system_backend/namespace.rst
Labels: documentation

#510 Release v0.9.5
  .bumpversion.cfg
  CHANGELOG.md
  CONTRIBUTING.md
  docs/conf.py
  docs/usage/system_backend/index.rst
  docs/usage/system_backend/namespace.rst
  hvac/api/secrets_engines/__init__.py
  hvac/api/secrets_engines/active_directory.py
  setup.py
Labels: release

#511 Fix Typo In PKI list_certificates Documentation
  docs/usage/secrets_engines/pki.rst
Labels: documentation, skip-changelog
