Repository hvac/hvac, pull requests merged in 2020-12, with the labels that each got.

#653 fix health.py read_health_status GET method
  hvac/api/system_backend/health.py
Labels: bug, system backend

#651 Template "auth method not implemented" error message
  hvac/api/vault_api_category.py
Labels: auth methods, bug

#649 Enable response wrapping of PKI secrets
  hvac/api/secrets_engines/pki.py
Labels: enhancement

#647 Minor change: Fix typo
  docs/usage/secrets_engines/pki.rst
Labels: documentation, skip-changelog
