Repository hvac/hvac, pull requests merged in 2020-05, with the labels that each got.

#583 Add request data to exception objects
  hvac/adapters.py
  hvac/exceptions.py
  hvac/utils.py
  tests/integration_tests/v1/test_integration.py
Labels: enhancement

#586 add vault rekey verification methods
  docs/usage/system_backend/key.rst
  hvac/api/system_backend/key.py
  tests/integration_tests/api/system_backend/test_key.py
Labels: enhancement, system backend

#571 Add license to sdist tarball
  setup.cfg
Labels: misc, skip-changelog

#589 Remove json() calls (unneeded following JSONAdapter addition)
  hvac/api/auth_methods/userpass.py
Labels: bug, userpass

#595 Release v0.10.3
  .bumpversion.cfg
  CHANGELOG.md
  docs/conf.py
  docs/usage/system_backend/index.rst
  docs/usage/system_backend/raft.rst
  hvac/api/auth_methods/ldap.py
  hvac/api/system_backend/__init__.py
  hvac/api/system_backend/raft.py
  setup.py
Labels: release
