Repository hvac/hvac, pull requests merged in 2020-06, with the labels that each got.

#598 Extract "renew_self_token" from "renew_token"
  hvac/v1/__init__.py
  tests/integration_tests/v1/test_integration.py
Labels: enhancement, token

#599 Update AWS Auth Docs With Latest Usage
  docs/usage/auth_methods/aws.rst
  hvac/api/auth_methods/aws.py
Labels: documentation

#587 Fix some code quality and bug-risk issues
  hvac/api/auth_methods/azure.py
  hvac/api/auth_methods/github.py
  hvac/api/secrets_engines/pki.py
  hvac/api/system_backend/auth.py
  hvac/utils.py
Labels: misc, skip-changelog

#600 Release v0.10.4
  .bumpversion.cfg
  CHANGELOG.md
  docs/conf.py
  docs/usage/auth_methods/aws.rst
  docs/usage/system_backend/leader.rst
  hvac/api/auth_methods/aws.py
  hvac/api/auth_methods/azure.py
  hvac/api/auth_methods/github.py
  hvac/api/secrets_engines/pki.py
  hvac/api/system_backend/auth.py
  hvac/api/system_backend/leader.py
  hvac/utils.py
  hvac/v1/__init__.py
  setup.py
  tests/integration_tests/v1/test_integration.py
Labels: release
