Repository hvac/hvac, pull requests merged in 2021-07, with the labels that each got.

#720 Fix Cert.login() handling of use_token argument
  hvac/api/auth_methods/cert.py
Labels: bug, tls-cert-auth

#727 Add `python_requires='>=2.7'` to setuptools Metadata
  setup.py
Labels: meta, misc

#728 Update Deprecated Usage In Documentation & Tests
  docs/usage/auth_methods/azure.rst
  docs/usage/auth_methods/gcp.rst
  docs/usage/auth_methods/github.rst
  docs/usage/auth_methods/ldap.rst
  docs/usage/auth_methods/mfa.rst
  docs/usage/auth_methods/okta.rst
  tests/integration_tests/api/auth_methods/test_approle.py
  tests/integration_tests/api/auth_methods/test_azure.py
  tests/integration_tests/api/auth_methods/test_cert.py
  tests/integration_tests/api/auth_methods/test_gcp.py
  tests/integration_tests/api/auth_methods/test_github.py
  tests/integration_tests/api/auth_methods/test_kubernetes.py
  tests/integration_tests/api/auth_methods/test_ldap.py
  tests/integration_tests/api/auth_methods/test_mfa.py
  tests/integration_tests/api/auth_methods/test_oidc.py
  tests/integration_tests/api/secrets_engines/test_aws.py
  tests/integration_tests/api/secrets_engines/test_azure.py
  tests/integration_tests/api/secrets_engines/test_gcp.py
  tests/integration_tests/api/secrets_engines/test_kv_v1.py
  tests/integration_tests/api/secrets_engines/test_kv_v2.py
  tests/integration_tests/api/secrets_engines/test_pki.py
  tests/integration_tests/api/secrets_engines/test_transform.py
  tests/integration_tests/api/secrets_engines/test_transit.py
  tests/integration_tests/api/system_backend/test_lease.py
  tests/integration_tests/api/system_backend/test_mount.py
  tests/integration_tests/api/system_backend/test_policy.py
  tests/integration_tests/v1/test_approle.py
  tests/integration_tests/v1/test_integration.py
  tests/integration_tests/v1/test_system_backend.py
  tests/unit_tests/v1/test_approle_routes.py
  tests/unit_tests/v1/test_auth_methods.py
  tests/unit_tests/v1/test_aws_ec2_methods.py
  tests/unit_tests/v1/test_aws_iam_methods.py
  tests/unit_tests/v1/test_gcp_methods.py
  tests/unit_tests/v1/test_kubernetes_methods.py
  tests/unit_tests/v1/test_system_backend_methods.py
  tests/utils/__init__.py
  tests/utils/hvac_integration_test_case.py
  tests/utils/mock_github_request_handler.py
  tests/utils/mock_okta_request_handler.py
Labels: CI/CD, misc

#730 Deprecate AppID-related `Client()` Methods
  hvac/utils.py
  hvac/v1/__init__.py
Labels: misc

#731 Add deprecation notices for `Client()` approle methods
  hvac/v1/__init__.py
Labels: approle, misc

#732 Add deprecation notices for `Client()` k8s methods
  hvac/v1/__init__.py
Labels: kubernetes, misc

#733 Userpass: Add `use_token` param on `login()`, Accept passthrough `**kwargs` on create user
  hvac/api/auth_methods/userpass.py
Labels: breaking-change, enhancement, userpass

#734 Migrate Token Auth Methods to Dedicated Class
  docs/usage/auth_methods/token.rst
  hvac/api/auth_methods/__init__.py
  hvac/api/auth_methods/token.py
  hvac/v1/__init__.py
  tests/integration_tests/api/auth_methods/test_token.py
  tests/integration_tests/v1/test_system_backend.py
Labels: enhancement, token

#735 Support CA-related Environment Variables
  hvac/adapters.py
  hvac/constants/client.py
  hvac/v1/__init__.py
  tests/unit_tests/test_adapters.py
Labels: enhancement

#737 Restore Flake8 to PR Workflow
  .github/workflows/lint-and-test.yml
  hvac/api/auth_methods/cert.py
  hvac/api/auth_methods/kubernetes.py
  requirements-dev.in
  requirements-dev.txt
  tests/integration_tests/api/auth_methods/test_cert.py
  tests/unit_tests/v1/test_auth_methods.py
Labels: CI/CD, skip-changelog

#740 Enable Sphinx `doctests` in GH Actions PR Workflow
  .github/workflows/lint-and-test.yml
  docs/usage/system_backend/key.rst
  tests/config_files/pgp_key.asc.b64
Labels: CI/CD, documentation, misc

#742 Tiny Bit of Additional flake8-related Changes
  .flake8
  README.md
  docs/ext/hvac_doctest.py
Labels: CI/CD, skip-changelog
