Repository hvac/hvac, pull requests merged in 2021-04, with the labels that each got.

#680 Send AppRole generate_secret_id Method Metadata Parameter as String
  hvac/api/auth_methods/approle.py
Labels: approle, bug

#681 Release v0.10.9
  .bumpversion.cfg
  CHANGELOG.md
  docs/conf.py
  docs/usage/auth_methods/aws.rst
  docs/usage/secrets_engines/pki.rst
  hvac/api/auth_methods/approle.py
  setup.py
Labels: release

#688 Set daemon attribute instead of using setDaemon method that was deprecated in Python 3.10
  tests/integration_tests/api/auth_methods/test_github.py
Labels: CI/CD, misc

#689 Add handling of unsupported HTTP methods inside adapter
  hvac/adapters.py
Labels: enhancement

#562 Add `policies` Parameter to Userpass `create_or_update_user()` Method
  hvac/api/auth_methods/userpass.py
Labels: enhancement, userpass

#657 Add Active Directory generate credential capability
  docs/usage/secrets_engines/activedirectory.rst
  docs/usage/secrets_engines/index.rst
  hvac/api/secrets_engines/active_directory.py
Labels: active directory, enhancement

#684 AWS Secrets Engine: Add support for iam_tags when creating roles
  hvac/api/secrets_engines/aws.py
Labels: aws, enhancement

#690 Release v0.10.10
  .bumpversion.cfg
  CHANGELOG.md
  docs/conf.py
  docs/usage/secrets_engines/activedirectory.rst
  docs/usage/secrets_engines/index.rst
  hvac/adapters.py
  hvac/api/auth_methods/userpass.py
  hvac/api/secrets_engines/active_directory.py
  hvac/api/secrets_engines/aws.py
  hvac/api/secrets_engines/kv_v2.py
  setup.py
  tests/integration_tests/api/auth_methods/test_github.py
Labels: release

#692 Set copied docstring content to "N/A" when no source docstring present
  hvac/utils.py
Labels: misc, skip-changelog
