Repository hvac/hvac, pull requests merged in 2021-05, with the labels that each got.

#695 Bump versions of Vault used in CI workflows
  .github/workflows/python-package.yml
  README.md
Labels: CI/CD

#694 Add `delete_version_after` KvV2 Param - `configure()` / `update_metadata()
  docs/usage/secrets_engines/kv_v2.rst
  hvac/api/secrets_engines/kv_v2.py
  tests/integration_tests/api/secrets_engines/test_kv_v2.py
Labels: enhancement, kv

#696 Expand Transform class to include new(ish) tokenization methods
  docs/usage/secrets_engines/transform.rst
  hvac/api/secrets_engines/transform.py
  tests/integration_tests/api/secrets_engines/test_transform.py
Labels: enhancement, transform

#701 Update approle.rst
  docs/usage/auth_methods/approle.rst
Labels: documentation, skip-changelog

#691 Add Certificate Authentication Methods
  hvac/api/auth_methods/__init__.py
  hvac/api/auth_methods/cert.py
  hvac/v1/__init__.py
  tests/integration_tests/api/auth_methods/test_cert.py
Labels: enhancement, tls-cert-auth

#703 Add default to `group_type` argument in `update_group` and `create_or_update_group_by_name`
  hvac/api/secrets_engines/identity.py
Labels: enhancement, identity

#704 Release v0.10.12
  .bumpversion.cfg
  CHANGELOG.md
  docs/conf.py
  docs/usage/auth_methods/approle.rst
  hvac/api/auth_methods/__init__.py
  hvac/api/auth_methods/cert.py
  hvac/api/secrets_engines/identity.py
  hvac/v1/__init__.py
  setup.py
  tests/integration_tests/api/auth_methods/test_cert.py
Labels: release

#708 Refactor `Cert.login()` Conditional for Python 2.7 Syntax Support
  hvac/api/auth_methods/cert.py
Labels: bug

#709 Release v0.10.13
  hvac/api/auth_methods/cert.py
Labels: release

#710 Release v0.10.13 (take two)
  .bumpversion.cfg
  CHANGELOG.md
  docs/conf.py
  setup.py
Labels: release

#712 Python 2.7: Drop Trailing Comma In `Cert.login()`
  hvac/api/auth_methods/cert.py
Labels: bug

#713 Release v0.10.14
  .bumpversion.cfg
  CHANGELOG.md
  docs/conf.py
  hvac/api/auth_methods/cert.py
  setup.py
Labels: release
