Repository hvac/hvac, pull requests merged in 2022-07, with the labels that each got.

#826 Bump dependencies
  requirements-dev.txt
  requirements.txt
  tests/utils/mock_oauth_provider/routes.py
Labels: dependencies

#827 Update kubernetes authentication example
  docs/usage/auth_methods/kubernetes.rst
Labels: documentation

#844 build-test: Add test
  .github/workflows/build-test.yml
Labels: CI/CD

#843 setup.py: Add encoding for long_description
  setup.py
Labels: bug
