Repository hvac/hvac, pull requests merged in 2023-02, with the labels that each got.

#942 doc: update reference to removed method
  hvac/v1/__init__.py
Labels: documentation

#775 Create userpass.rst
  docs/usage/auth_methods/index.rst
  docs/usage/auth_methods/userpass.rst
Labels: documentation

#903 Add new field `auto_rotate_period` on transit key management
  hvac/api/secrets_engines/transit.py
  tests/integration_tests/api/secrets_engines/test_transit.py
Labels: enhancement, transit

#805 Add support for custom metadata in kv2 engine
  docs/usage/secrets_engines/kv_v2.rst
  hvac/api/secrets_engines/kv_v2.py
  tests/integration_tests/api/secrets_engines/test_kv_v2.py
Labels: enhancement, secrets engines, kv

#949 docs - sphinx - fail on warnings
  CHANGELOG.md
  README.md
  docs/Makefile
  hvac/api/auth_methods/cert.py
  poetry.lock
  pyproject.toml
Labels: documentation, CI/CD

#948 add documentation for retries
  docs/advanced_usage.rst
Labels: documentation

#934 AWS secret engine - fix `generate_credentials` for STS endpoint
  hvac/api/secrets_engines/aws.py
Labels: bug, enhancement, aws, secrets engines, minor
