Repository hvac/hvac, pull requests merged in 2023-06, with the labels that each got.

#1000 update publishing workflow
  .github/workflows/python-publish.yml
Labels: skip-changelog, maintenance

#1003 update workflows and CI for new git/release process
  .github/config.yml
  .github/release-drafter.yml
  .github/workflows/build-test.yml
  .github/workflows/lint-and-test.yml
  .github/workflows/release-drafter.yml
  CONTRIBUTING.md
Labels: documentation, skip-changelog, maintenance

#1002 update publishing workflow
  .github/workflows/python-publish.yml
Labels: skip-changelog, maintenance

#1004 PyPI publish follow-up
  .github/workflows/python-publish.yml
Labels: skip-changelog, maintenance

#997 feat: add support for `disable_local_ca_jwt` in the Kubernetes auth method
  hvac/api/auth_methods/kubernetes.py
  tests/integration_tests/api/auth_methods/test_kubernetes.py
Labels: auth methods, kubernetes

#982 fix(`__getattr__`): non-existent attribute lookup
  hvac/api/secrets_engines/kv.py
  hvac/api/vault_api_category.py
Labels: bug, secrets engines, kv

#1009 Add a method to read static roles in the database engine
  hvac/api/secrets_engines/database.py
Labels: enhancement, secrets engines, database

#1010 docs: make OIDC Authorization URL Request example work again.
  docs/usage/auth_methods/jwt-oidc.rst
Labels: documentation, auth methods, jwt/oidc

#990 adding batch_input to transit.sign_data #988
  hvac/api/secrets_engines/transit.py
Labels: enhancement, secrets engines, transit

#1016 Versioning updates
  .bumpversion.cfg
  CONTRIBUTING.md
  docs/conf.py
  poetry.lock
  pyproject.toml
Labels: documentation, meta, dependencies, skip-changelog, maintenance

#1015 add tests and docs to sdist, improve build testing
  .github/workflows/build-test.yml
  .github/workflows/python-publish.yml
  pyproject.toml
Labels: CI/CD, meta, tests

#1019 retain build compat with py3.6
  pyproject.toml
Labels: CI/CD, skip-changelog, tests, maintenance

#956 Add static account support to GCP secrets engine
  hvac/api/secrets_engines/gcp.py
  tests/unit_tests/api/secrets_engines/test_gcp.py
Labels: enhancement, gcp, secrets engines
