Repository hvac/hvac, pull requests merged in 2023-01, with the labels that each got.

#933 pin to ubuntu 20.04 until 3.6 is dropped
  .github/workflows/build-test.yml
  .github/workflows/lint-and-test.yml
  .github/workflows/python-publish.yml
  .github/workflows/release-drafter.yml
Labels: CI/CD

#789 Update wrapping.rst - example for unauthenticated unwrap
  docs/usage/system_backend/wrapping.rst
Labels: documentation

#939 Propagate client's adapter to API categories
  hvac/api/system_backend/__init__.py
  hvac/v1/__init__.py
  tests/unit_tests/v1/test_client.py
Labels: bug, adapters

#935 Update Azure guideline with proper client variable
  docs/usage/auth_methods/azure.rst
Labels: documentation
