Repository hvac/hvac, pull requests merged in 2023-10, with the labels that each got.

#1063 Changing default values for `sys.initialize` parameters `secret_shares` and `secret_threshold`
  hvac/api/system_backend/init.py
  tests/integration_tests/api/system_backend/test_init.py
  tests/unit_tests/api/auth_methods/test_token.py
  tests/unit_tests/api/system_backend/test_init.py
  tests/unit_tests/conftest.py
Labels: bug, system backend, breaking-change, announcement

#1072 Fix invalid build and test status
  README.md
Labels: documentation, CI/CD, meta, developer experience

#1069 Database Secrets Engine - add `rotate_static_credentials` method, docs updates, unit tests
  docs/usage/secrets_engines/database.rst
  hvac/api/secrets_engines/database.py
  tests/unit_tests/api/secrets_engines/test_database.py
Labels: enhancement, documentation, secrets engines, database

#1084 drop python-jwt dev dependency
  poetry.lock
  pyproject.toml
Labels: dependencies, misc, tests

#1085 Release process - use `poetry-bumpversion` instead of `bump2version`
  .bumpversion.cfg
  CONTRIBUTING.md
  poetry.lock
  pyproject.toml
Labels: dependencies, skip-changelog

#1087 add .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: misc, developer experience

#1073 Add support for Python 3.12
  .flake8
  .github/workflows/build-test.yml
  .github/workflows/lint-and-test.yml
  .readthedocs.yaml
  poetry.lock
  pyproject.toml
Labels: CI/CD, dependencies

#1074 Drop support for Vault 1.6-1.10
  .github/workflows/lint-and-test.yml
Labels: CI/CD, breaking-change, announcement

#1086 update docstring for sys step-down
  hvac/api/system_backend/leader.py
Labels: documentation, system backend

#1089 `Client.write` method breaking changes 2.0.0
  hvac/v1/__init__.py
  poetry.lock
  pyproject.toml
  tests/integration_tests/v1/test_system_backend.py
  tests/unit_tests/v1/test_system_backend_methods.py
  tests/utils/__init__.py
Labels: dependencies, breaking-change, client

#1091 Release/v2.0.0
  CHANGELOG.md
  CONTRIBUTING.md
  docs/conf.py
  pyproject.toml
Labels: release

#1103 Add Vault 1.15.x to integration tests
  .github/workflows/lint-and-test.yml
  tests/integration_tests/api/auth_methods/test_kubernetes.py
Labels: auth methods, CI/CD, kubernetes, misc, patch, tests

#1099 Update GCP secrets engine documentation
  docs/usage/secrets_engines/gcp.rst
  hvac/api/secrets_engines/gcp.py
Labels: gcp, documentation, secrets engines, patch

#1102 Add support to PKI class to perform CRUD on issuers
  docs/usage/secrets_engines/pki.rst
  hvac/api/secrets_engines/pki.py
  tests/integration_tests/api/secrets_engines/test_pki.py
Labels: enhancement, documentation, secrets engines, minor, hacktoberfest-accepted, pki
