Repository hvac/hvac, pull requests merged in 2023-03, with the labels that each got.

#782 approle - fix metadata for generated secret IDs, re-add `wrap_ttl`
  hvac/api/auth_methods/approle.py
  tests/integration_tests/api/auth_methods/test_approle.py
  tests/unit_tests/api/auth_methods/test_approle.py
Labels: bug, auth methods, approle

#943 fix vault client certificates loaded from envirnoment variables
  hvac/v1/__init__.py
  poetry.lock
  pyproject.toml
  tests/integration_tests/api/auth_methods/test_cert.py
  tests/utils/__init__.py
  tests/utils/hvac_integration_test_case.py
Labels: bug

#907 Allow for reading deleted secret versions (kv2) without an exception
  hvac/adapters.py
  hvac/api/secrets_engines/kv_v2.py
  hvac/exceptions.py
  hvac/utils.py
  tests/integration_tests/api/secrets_engines/test_kv_v2.py
  tests/unit_tests/api/secrets_engines/test_kv.py
  tests/unit_tests/test_adapters.py
Labels: bug, enhancement, secrets engines, kv

#952 Release drafter/updates
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: CI/CD, skip-changelog

#953 release_drafter - make issue links actual markdown links
  .github/release-drafter.yml
Labels: CI/CD, skip-changelog
