Repository hvac/hvac, pull requests merged in 2024-01, with the labels that each got.

#1120 `Client.write_data` - remove potentially dangerous default
  hvac/v1/__init__.py
Labels: bug, patch, client

#1111 :pencil: Add HTTP/2+ use case into the advanced usage section
  CONTRIBUTING.md
  docs/contrib/index.rst
  docs/contrib/niquests_http2.rst
  docs/index.rst
Labels: documentation, patch, adapters, client

#1124 Release/v2.1.0
  CHANGELOG.md
  docs/conf.py
  pyproject.toml
Labels: release

#1123 refactor: move identity DEFAULT_MOUNT_POINT to constants
  hvac/api/auth_methods/okta.py
  hvac/api/secrets_engines/identity.py
  hvac/constants/identity.py
Labels: secrets engines, identity, misc, patch, maintenance

#1125 aws auth - add support for `iam_metadata` and `ec2_metadata` params
  hvac/api/auth_methods/aws.py
  tests/integration_tests/api/auth_methods/test_aws.py
Labels: enhancement, aws, auth methods, minor

#1126 Enable dependabot for GitHub Actions
  .github/dependabot.yml
Labels: CI/CD, dependencies, misc, skip-changelog, maintenance
