Repository hvac/hvac, pull requests merged in 2024-06, with the labels that each got.

#1172 Implement the /sys/wrapping/wrap endpoint
  hvac/api/system_backend/wrapping.py
  tests/integration_tests/api/system_backend/test_wrapping.py
Labels: enhancement, system backend, minor

#1173 update artifact actions to v4
  .github/workflows/build-test.yml
  .github/workflows/lint-and-test.yml
  .github/workflows/release.yml
Labels: CI/CD, misc, patch

#1174 Dependencies/security updates
  poetry.lock
  pyproject.toml
Labels: dependencies, misc, patch

#1175 Release/v2.3.0
  CHANGELOG.md
  docs/conf.py
  pyproject.toml
Labels: release
